sudo: required
os: linux

before_install:
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:tmate.io/archive
    - sudo apt-get update
    - sudo apt-get install -y tmate bash curl ssh
    - echo -e "\n\n\n\n\n" | ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -N ""

script:
    - tmate -S /tmp/tmate.sock new-session -d
    - tmate -S /tmp/tmate.sock wait tmate-ready
    - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
    - ping 8.8.8.8
